import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import { SessionProvider } from "next-auth/react";

import { TRPCReactProvider } from "~/trpc/react";
import AuthStatusDisplay from "./_components/AuthStatusDisplay";
import TransitionLink from "./_components/TransitionLink";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <SessionProvider>
          <header className="bg-white/10 p-4">
            <div className="container mx-auto flex items-center justify-between">
              <TransitionLink href="/" className="text-2xl font-bold text-white">
                T3 App
              </TransitionLink>
              <AuthStatusDisplay />
            </div>
          </header>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
